[profile.default]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

solc = "0.8.25"
optimizer = true
optimizer_runs = 100000

evm_version = "cancun"

remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "rain.factory/=lib/rain.factory/src/",
    "rain.intorastring/=lib/rain.interpreter/lib/rain.intorastring/src/",
    "rain.flare/=lib/rain.flare/src/",
    "chainlink/=lib/rain.chainlink/lib/chainlink/contracts/src/",
    "rain.math.fixedpoint/=lib/rain.math.fixedpoint/src/",
    "rain.extrospection/=lib/rain.factory/lib/rain.extrospection/src/",
    "rain.math.float/=lib/rain.flare/lib/rain.interpreter/lib/rain.interpreter.interface/lib/rain.math.float/src/",
]

bytecode_hash = "none"
cbor_metadata = false